pub mod auth;
pub mod cli;
pub mod cli_handlers;
pub mod cli_response;
pub mod config;
pub mod executor;
pub mod error;
pub mod gui;
pub mod pipe;
pub mod file_transfer;
pub mod output;
pub mod proto;
pub mod service;
pub mod registry;
pub mod script;
pub mod settings;
pub mod profile;

pub use auth::{AuthContext, AuthMethod};
pub use cli_response::{ServiceInfo as CliServiceInfo, ServiceState as CliServiceState, ServiceListResponse, RegistryEntryInfo, RegistryListResponse, ScriptExecResult, OperationResult, CliResponse};
pub use executor::{ExecutionContext, ExecutionMethod, ExecutionResult};
pub use error::{PaExecError, RetryPolicy, Result};
pub use pipe::InteractiveSession;
pub use file_transfer::{FileTransferContext, TransferResult, TransferDirection, TransferMethod, FileMetadata};
pub use output::{OutputFetchContext, OutputResult, OutputMethod, OutputFetcher, fetch_output};
pub use service::{ServiceContext, ServiceInfo, ServiceState, ServiceStartupType, ServiceResult};
pub use registry::{RegistryContext, RegistryHive, RegistryValue, RegistryValueType, RegistryEntry};
pub use script::{ScriptContext, ScriptExecution, ScriptResult, ScriptType, ExecutionPolicy};
pub use profile::{ExecutionProfile, ProfileSettings, SavedCommand, ProfileHost, ProfileManager};
