name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    name: Create Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: Build release binary
        run: cargo build --release --verbose

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/psexec_rs.exe
            README.md
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to release
        uses: actions/upload-artifact@v3
        with:
          name: psexec-rs-${{ github.ref_name }}
          path: target/release/psexec_rs.exe
